import { appPage } from "./app";

const STYLE = `<style>
.next-launch{display:flex;align-items:center;gap:8px;margin:10px 0 0;border:1px solid var(--line);background:transparent;color:var(--muted);border-radius:10px;padding:10px 11px;font:600 12px Manrope;cursor:pointer}.next-launch:hover{color:var(--text);border-color:var(--line2);background:rgba(255,255,255,.035)}
.next-launch b{display:grid;place-items:center;width:19px;height:19px;border-radius:6px;background:var(--green-dim);color:var(--green);font:11px 'DM Mono'}.next-search{width:100%;margin-top:12px;border:1px solid var(--line);background:#09090a;color:var(--text);border-radius:10px;padding:9px 10px;font:12px Manrope;outline:0}.next-search:focus{border-color:rgba(52,209,126,.5)}
.next-drawer{position:fixed;z-index:110;inset:10px 10px 10px auto;width:min(720px,calc(100vw - 20px));display:grid;grid-template-rows:auto auto minmax(0,1fr);background:#0b0b0c;border:1px solid var(--line2);border-radius:18px;box-shadow:0 36px 120px rgba(0,0,0,.72);transform:translateX(calc(100% + 24px));transition:transform .2s ease;overflow:hidden}.next-drawer.open{transform:none}.next-backdrop{position:fixed;z-index:109;inset:0;background:rgba(0,0,0,.62);opacity:0;pointer-events:none;transition:opacity .2s}.next-backdrop.open{opacity:1;pointer-events:auto}
.next-head{display:flex;align-items:center;gap:12px;padding:18px 20px;border-bottom:1px solid var(--line)}.next-head h2{font:700 21px 'Playfair Display';margin:0}.next-head small{color:var(--faint);font:10px 'DM Mono';text-transform:uppercase;letter-spacing:.08em}.next-spacer{flex:1}.next-icon{display:grid;place-items:center;width:34px;height:34px;border:1px solid var(--line);background:transparent;color:var(--muted);border-radius:10px;cursor:pointer}.next-icon:hover{color:var(--text);border-color:var(--line2)}
.next-tabs{display:flex;gap:4px;padding:10px 14px;border-bottom:1px solid var(--line);overflow-x:auto;scrollbar-width:none}.next-tab{flex:none;border:0;background:transparent;color:var(--faint);border-radius:9px;padding:8px 10px;font:600 11px Manrope;cursor:pointer}.next-tab:hover{color:var(--text)}.next-tab.active{background:var(--panel2);color:var(--text);box-shadow:inset 0 0 0 1px var(--line)}
.next-body{overflow-y:auto;padding:18px 20px 42px;overscroll-behavior:contain}.next-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.next-card{border:1px solid var(--line);background:#0e0e10;border-radius:14px;padding:15px}.next-card h3{font-size:14px;margin:0 0 5px}.next-card p{color:var(--muted);font-size:12px;line-height:1.55;margin:0}.next-row{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.next-list{display:grid;gap:7px;margin-top:12px}.next-item{display:flex;align-items:flex-start;gap:10px;border:1px solid var(--line);border-radius:11px;padding:11px;background:#0a0a0b}.next-item-main{flex:1;min-width:0}.next-item b{font-size:12px}.next-item small{display:block;color:var(--faint);font-size:10px;margin-top:3px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.next-btn{border:1px solid var(--line2);background:var(--panel2);color:var(--text);border-radius:9px;padding:8px 10px;font:600 11px Manrope;cursor:pointer}.next-btn:hover{border-color:rgba(52,209,126,.45)}.next-btn.primary{border-color:transparent;background:var(--green);color:#03140b}.next-btn.danger{color:#ff9a9a}.next-btn[disabled]{opacity:.45;cursor:default}
.next-input,.next-select,.next-area{width:100%;border:1px solid var(--line2);background:#080809;color:var(--text);border-radius:10px;padding:10px 11px;font:12px Manrope;outline:0}.next-area{resize:vertical;min-height:110px;line-height:1.55}.next-input:focus,.next-select:focus,.next-area:focus{border-color:rgba(52,209,126,.55);box-shadow:0 0 0 3px rgba(52,209,126,.07)}.next-label{display:block;color:var(--muted);font:10px 'DM Mono';letter-spacing:.06em;text-transform:uppercase;margin:12px 0 6px}.next-status{border-left:2px solid var(--green);padding:8px 10px;margin-top:10px;color:var(--muted);font-size:11px;line-height:1.5;background:var(--green-dim)}
.next-attachments{display:flex;gap:6px;flex-wrap:wrap;padding:0 4px 7px}.next-attachment{display:flex;gap:7px;align-items:center;border:1px solid var(--line);background:var(--panel2);color:var(--muted);border-radius:999px;padding:6px 9px;font-size:10px}.next-attachment button{border:0;background:transparent;color:var(--faint);cursor:pointer;padding:0}.next-composer-btn{border:1px solid var(--line);background:transparent;color:var(--muted);border-radius:9px;padding:7px 9px;font:600 11px Manrope;cursor:pointer}.next-composer-btn:hover{color:var(--text);border-color:var(--line2)}
.next-canvas{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:10px;min-height:400px}.next-canvas textarea{min-height:400px}.next-preview{width:100%;height:100%;min-height:400px;border:1px solid var(--line);border-radius:10px;background:#fff}.next-table{width:100%;border-collapse:collapse;font-size:11px;margin-top:10px;display:block;overflow:auto}.next-table th,.next-table td{border:1px solid var(--line);padding:7px 8px;text-align:left;white-space:nowrap}.next-chart{width:100%;height:260px;border:1px solid var(--line);border-radius:10px;margin-top:10px;background:#080809}
.next-media{position:fixed;z-index:130;right:20px;bottom:20px;width:min(480px,calc(100vw - 40px));border:1px solid var(--line2);background:#09090a;border-radius:16px;padding:10px;box-shadow:0 24px 90px #000}.next-media video{width:100%;max-height:320px;border-radius:10px;background:#000}.next-media[hidden]{display:none}.next-notify{position:fixed;z-index:150;right:18px;top:18px;display:grid;gap:7px;max-width:330px}.next-toast{border:1px solid rgba(52,209,126,.35);background:#0b1711;color:var(--text);border-radius:11px;padding:11px 13px;font-size:12px;box-shadow:0 14px 42px #000}.next-source{display:block;margin:8px 0;border-left:2px solid var(--green);padding-left:10px;color:var(--muted);font-size:11px}
.light .next-drawer,.light .next-card,.light .next-item{background:#fff}.light .next-input,.light .next-select,.light .next-area,.light .next-search,.light .next-chart{background:#fafafa;color:#151515}
@media(max-width:760px){.next-drawer{inset:4px;width:calc(100vw - 8px);border-radius:16px}.next-body{padding:14px 14px 36px}.next-grid,.next-canvas{grid-template-columns:1fr}.next-canvas textarea,.next-preview{min-height:300px}.next-launch{display:none}.next-composer-btn{min-height:42px}.next-media{right:8px;bottom:8px;width:calc(100vw - 16px)}}
@media(prefers-reduced-motion:reduce){.next-drawer,.next-backdrop{transition:none}}
</style>`;

const SCRIPT = `<script>(function(){
const pstate={tab:'home',data:null,pending:[],assistant:null,document:null,dataRows:[],browserSession:null,notified:new Set(),research:null};
const pq=s=>document.querySelector(s),pqa=s=>Array.from(document.querySelectorAll(s)),esc=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ptext=x=>typeof x==='string'?x:Array.isArray(x)?x.map(v=>v&&v.text||'').join('\\n'):'';
async function papi(path,init={}){const response=await fetch('/studio/api/platform'+path,{credentials:'same-origin',headers:{'content-type':'application/json',...(init.headers||{})},...init});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof data.message==='string'?data.message:typeof data.error==='string'?data.error:'Request failed');return data}
function toast(text){const host=pq('#nextNotify'),el=document.createElement('div');el.className='next-toast';el.textContent=text;host.append(el);setTimeout(()=>el.remove(),4200)}
function openNext(tab){pstate.tab=tab||pstate.tab;pq('#nextDrawer').classList.add('open');pq('#nextBackdrop').classList.add('open');pq('#nextDrawer').setAttribute('aria-hidden','false');renderNext();setTimeout(()=>pq('#nextClose').focus(),0)}
function closeNext(){pq('#nextDrawer').classList.remove('open');pq('#nextBackdrop').classList.remove('open');pq('#nextDrawer').setAttribute('aria-hidden','true')}
function tabs(){return [['home','Home'],['chats','Chats'],['memory','Memory'],['files','Files'],['research','Research'],['canvas','Canvas'],['data','Data'],['assistants','Assistants'],['tasks','Tasks'],['browser','Computer'],['more','More']].map(x=>'<button class="next-tab'+(pstate.tab===x[0]?' active':'')+'" data-next-tab="'+x[0]+'">'+x[1]+'</button>').join('')}
function requireData(){if(pstate.data)return '';return '<div class="next-card"><h3>Sign in to sync Studio</h3><p>Advanced workspaces, memory, files, research, assistants, background tasks, and cloud sessions require an OSAII Platform account.</p><button class="next-btn primary" id="nextSignIn" style="margin-top:12px">Sign in</button></div>'}
function card(title,body,actions=''){return '<div class="next-card"><h3>'+esc(title)+'</h3><p>'+body+'</p>'+actions+'</div>'}
function renderNext(){pq('#nextTabs').innerHTML=tabs();const body=pq('#nextBody');if(!pstate.data){body.innerHTML=requireData();pq('#nextSignIn')?.addEventListener('click',()=>{closeNext();document.querySelector('[data-studio-panel="account"]')?.click()});bindTabs();return}const views={home:homeView,chats:chatsView,memory:memoryView,files:filesView,research:researchView,canvas:canvasView,data:dataView,assistants:assistantsView,tasks:tasksView,browser:browserView,more:moreView};body.innerHTML=(views[pstate.tab]||homeView)();bindTabs();bindView()}
function bindTabs(){pqa('[data-next-tab]').forEach(b=>b.onclick=()=>{pstate.tab=b.dataset.nextTab;renderNext()})}
function homeView(){const unread=(pstate.data.notifications||[]).filter(x=>!Number(x.read)).length;return '<div class="next-grid">'+card('Continue anywhere','Your chats, projects, memory, and background sessions are synced.','<button class="next-btn" data-next-tab="chats" style="margin-top:12px">Open chats</button>')+card('Background work',(pstate.data.tasks||[]).filter(x=>x.status==='running'||x.status==='scheduled').length+' active or scheduled · '+unread+' unread notifications.','<button class="next-btn" data-next-tab="tasks" style="margin-top:12px">View tasks</button>')+card('Research mode','Editable plan, autonomous browsing, source restrictions, progress, citations, and export.','<button class="next-btn" data-next-tab="research" style="margin-top:12px">Start research</button>')+card('Create deliverables','Write, preview, share, remix, and export documents, code, apps, data, DOCX, XLSX, PPTX, and PDF.','<button class="next-btn" data-next-tab="canvas" style="margin-top:12px">Open Canvas</button>')+'</div><div class="next-card" style="margin-top:10px"><h3>Quick modes</h3><div class="next-row" style="margin-top:10px"><button class="next-btn" data-quick="study">Study with Socratic questions</button><button class="next-btn" data-quick="meeting">Record or transcribe a meeting</button><button class="next-btn" data-quick="code">Open coding workspace</button><button class="next-btn" data-install>Install OSS Studio</button></div></div>'}
function chatsView(){return '<div class="next-row"><input class="next-input" id="chatSearch" placeholder="Search every synced conversation" style="flex:1"><button class="next-btn" id="chatSearchGo">Search</button></div><label class="next-label"><input type="checkbox" id="showArchived"> Show archived</label><div class="next-list" id="chatResults">'+chatItems(pstate.data.chats||[])+'</div>'}
function chatItems(rows){return rows.length?rows.map(c=>'<div class="next-item"><div class="next-item-main"><b>'+esc(Number(c.pinned)?'📌 '+c.title:c.title)+'</b><small>'+esc(c.mode)+' · '+esc(c.updated_at||'synced')+'</small></div><button class="next-btn" data-chat-open="'+esc(c.id)+'">Open</button><button class="next-btn" data-chat-pin="'+esc(c.id)+'" data-value="'+(Number(c.pinned)?'0':'1')+'">'+(Number(c.pinned)?'Unpin':'Pin')+'</button><button class="next-btn" data-chat-more="'+esc(c.id)+'">•••</button></div>').join(''):'<div class="next-card"><p>No matching chats.</p></div>'}
function memoryView(){const memories=pstate.data.memories||[];return '<div class="next-card"><h3>Memory control center</h3><p>Inspect exactly what Studio remembers. Project memories ground every chat in that project; personal memories apply everywhere.</p><label class="next-label">New memory</label><textarea class="next-area" id="memoryText" placeholder="A preference, fact, decision, or standing instruction"></textarea><div class="next-row" style="margin-top:8px"><select class="next-select" id="memoryProject" style="flex:1"><option value="">Personal memory</option>'+projectOptions()+'</select><button class="next-btn primary" id="memorySave">Remember</button><button class="next-btn" id="memoryImport">Import</button><button class="next-btn" id="memoryExport">Export</button><input id="memoryImportFile" type="file" accept="application/json" hidden></div></div><div class="next-list">'+(memories.length?memories.map(m=>'<div class="next-item"><div class="next-item-main"><b>'+esc(m.project_id?'Project memory':'Personal memory')+'</b><small style="white-space:normal">'+esc(m.content)+'</small></div><button class="next-btn" data-memory-pin="'+m.id+'">'+(Number(m.pinned)?'Unpin':'Pin')+'</button><button class="next-btn danger" data-memory-delete="'+m.id+'">Delete</button></div>').join(''):'<div class="next-card"><p>No saved memories yet.</p></div>')+'</div>'}
function filesView(){const a=pstate.data.attachments||[],project=activeProject();return '<div class="next-card"><h3>Files & project knowledge</h3><p>Upload PDFs, images, documents, spreadsheets, CSVs, and text. Extracted content automatically grounds the selected project.</p><div class="next-row" style="margin-top:10px"><button class="next-btn primary" id="fileChoose">Upload files</button><input id="fileInput" type="file" multiple accept=".pdf,.doc,.docx,.pptx,.xls,.xlsx,.csv,.tsv,.txt,.md,.json,image/*" hidden><select class="next-select" id="fileProject" style="flex:1"><option value="">No project</option>'+projectOptions(project?.id)+'</select></div><div class="next-status" id="fileStatus">Files are private and stored in your account.</div></div><div class="next-list">'+(a.length?a.map(x=>'<div class="next-item"><div class="next-item-main"><b>'+esc(x.name)+'</b><small>'+formatBytes(x.size)+' · '+esc(x.content_type)+' · '+(x.extracted_text?'text ready':'visual/binary')+'</small></div><a class="next-btn" href="/studio/api/platform/attachments/'+x.id+'/content" target="_blank">Open</a><button class="next-btn danger" data-file-delete="'+x.id+'">Delete</button></div>').join(''):'<div class="next-card"><p>No uploaded files.</p></div>')+'</div>'}
function researchView(){return '<div class="next-card"><h3>Research</h3><p>Review the plan before anything runs. Restrict sources by domain when needed.</p><label class="next-label">Question</label><textarea class="next-area" id="researchQuestion" placeholder="What should the research answer?">'+esc(pstate.research?.question||'')+'</textarea><label class="next-label">Editable plan</label><textarea class="next-area" id="researchPlan" placeholder="1. Define the decision and criteria&#10;2. Find primary sources&#10;3. Compare evidence and disagreements&#10;4. Produce cited conclusions">'+esc(pstate.research?.plan||'')+'</textarea><label class="next-label">Allowed domains (comma-separated, optional)</label><input class="next-input" id="researchDomains" placeholder="example.gov, arxiv.org"><div class="next-row" style="margin-top:10px"><button class="next-btn primary" id="researchRun">Run research</button><button class="next-btn" id="researchExport" '+(pstate.research?.report?'':'disabled')+'>Export report</button></div><div class="next-status" id="researchStatus">'+esc(pstate.research?.status||'Ready. The final report will show inline source numbers and URLs.')+'</div></div>'+(pstate.research?.report?'<div class="next-card" style="margin-top:10px"><h3>Cited report</h3><div id="researchReport" style="white-space:pre-wrap;line-height:1.7">'+esc(pstate.research.report)+'</div></div>':'')}
function canvasView(){const d=pstate.document||{title:'Untitled',kind:'document',content:''};return '<div class="next-row"><input class="next-input" id="canvasTitle" value="'+esc(d.title)+'" style="flex:1"><select class="next-select" id="canvasKind" style="width:auto"><option value="document">Document</option><option value="code">Code</option><option value="app">Live app</option><option value="report">Report</option></select><button class="next-btn primary" id="canvasSave">Save</button><button class="next-btn" id="canvasShare">Share</button><select class="next-select" id="canvasExport" style="width:auto"><option value="">Export…</option><option value="docx">DOCX</option><option value="xlsx">XLSX</option><option value="pptx">PPTX</option><option value="pdf">PDF</option><option value="html">HTML</option><option value="txt">Text</option></select></div><div class="next-canvas" style="margin-top:10px"><textarea class="next-area" id="canvasContent" placeholder="Write a document, code, or a complete HTML app…">'+esc(d.content)+'</textarea><iframe class="next-preview" id="canvasPreview" sandbox="allow-scripts"></iframe></div><div class="next-status">Canvas saves versioned work to your account. Live apps run in an isolated preview and can be shared or remixed.</div>'}
function dataView(){return '<div class="next-card"><h3>Data workspace</h3><p>Open CSV, TSV, or spreadsheet files; inspect the table, generate a chart, and export a real workbook.</p><div class="next-row" style="margin-top:10px"><button class="next-btn primary" id="dataOpen">Open data</button><input id="dataInput" type="file" accept=".csv,.tsv,.xlsx,.xls" hidden><select class="next-select" id="chartColumn" style="flex:1"></select><button class="next-btn" id="dataChart">Chart</button><button class="next-btn" id="dataExport">Export XLSX</button></div><div id="dataTable"></div><canvas class="next-chart" id="dataCanvas" width="900" height="300"></canvas></div>'}
function assistantsView(){const rows=pstate.data.assistants||[];return '<div class="next-card"><h3>Create an assistant</h3><p>Give it instructions, attach knowledge, and choose private, unlisted, or public discovery.</p><label class="next-label">Name</label><input class="next-input" id="assistantName"><label class="next-label">Description</label><input class="next-input" id="assistantDescription"><label class="next-label">Instructions</label><textarea class="next-area" id="assistantInstructions"></textarea><label class="next-label">Visibility</label><select class="next-select" id="assistantVisibility"><option value="private">Private</option><option value="unlisted">Unlisted</option><option value="public">Public catalog</option></select><button class="next-btn primary" id="assistantSave" style="margin-top:10px">Create assistant</button></div><div class="next-list">'+rows.map(a=>'<div class="next-item"><div class="next-item-main"><b>'+esc(a.icon||'✦')+' '+esc(a.name)+'</b><small>'+esc(a.description||a.visibility)+'</small></div><button class="next-btn" data-assistant-use="'+a.id+'">Use</button><button class="next-btn" data-assistant-remix="'+a.id+'">Remix</button></div>').join('')+'</div>'}
function tasksView(){const tasks=pstate.data.tasks||[],sessions=pstate.data.sessions||[];return '<div class="next-card"><h3>Cloud tasks</h3><p>Scheduled and background work continues after the tab or laptop closes. Completion appears in notifications.</p><label class="next-label">Task title</label><input class="next-input" id="taskTitle"><label class="next-label">Instructions</label><textarea class="next-area" id="taskPrompt"></textarea><div class="next-row" style="margin-top:8px"><select class="next-select" id="taskKind" style="flex:1"><option value="agent">Agent</option><option value="research">Research</option><option value="coding">Coding workspace</option><option value="reflection">Reflection</option></select><select class="next-select" id="taskSchedule" style="flex:1"><option value="">Run once</option><option value="every:30:minutes">Every 30 minutes</option><option value="every:1:hours">Hourly</option><option value="every:1:days">Daily</option><option value="every:7:days">Weekly</option></select><button class="next-btn primary" id="taskCreate">Schedule</button></div></div><div class="next-list">'+tasks.map(t=>'<div class="next-item"><div class="next-item-main"><b>'+esc(t.title)+'</b><small>'+esc(t.kind)+' · '+esc(t.status)+' · '+esc(t.progress||t.next_run||'ready')+'</small></div><button class="next-btn" data-task-run="'+t.id+'">Run now</button></div>').join('')+'</div><div class="next-card" style="margin-top:12px"><h3>Managed agent workspaces</h3><p>Sessions persist independently for agent, research, browser, cowork, and multi-agent coding work.</p><button class="next-btn" id="sessionCreate" style="margin-top:10px">New multi-agent coding workspace</button><div class="next-list">'+sessions.map(s=>'<div class="next-item"><div class="next-item-main"><b>'+esc(s.title)+'</b><small>'+esc(s.kind)+' · '+esc(s.status)+'</small></div></div>').join('')+'</div></div>'}
function browserView(){return '<div class="next-card"><h3>Computer use</h3><p>A real cloud browser opens the page and returns a visible screenshot. Navigation and reading are automatic; click and type always ask for confirmation.</p><label class="next-label">URL</label><input class="next-input" id="browserUrl" value="https://example.com"><div class="next-row" style="margin-top:8px"><select class="next-select" id="browserAction" style="flex:1"><option value="navigate">Navigate/read</option><option value="click">Click selector</option><option value="type">Type into selector</option></select><input class="next-input" id="browserSelector" placeholder="CSS selector for click/type" style="flex:1"><input class="next-input" id="browserValue" placeholder="Text to type" style="flex:1"><button class="next-btn primary" id="browserRun">Run</button></div><div class="next-status" id="browserStatus">Browser actions are audited in a managed session.</div><img id="browserShot" alt="Cloud browser screenshot" style="display:none;width:100%;margin-top:10px;border:1px solid var(--line);border-radius:10px"></div>'}
function moreView(){const profile=pstate.data.profile||{},market=pstate.data.marketplace||[],installs=new Set((pstate.data.installs||[]).map(x=>x.workflow_id));return '<div class="next-card"><h3>Preferences & custom instructions</h3><label class="next-label">What Studio should know and how it should respond</label><textarea class="next-area" id="customInstructions">'+esc(profile.custom_instructions||'')+'</textarea><label class="next-label"><input id="memoryEnabled" type="checkbox" '+(Number(profile.memory_enabled)!==0?'checked':'')+'> Use personal memory</label><button class="next-btn primary" id="profileSave">Save preferences</button></div><div class="next-card" style="margin-top:10px"><h3>Usage & reflection</h3><p>Standard account: 600 generations/minute, 6,000/hour, 20,000/day fair-use brakes. ChatGPT/Codex uses your connected account. Capacity is provider-neutral in Studio.</p><button class="next-btn" id="reflectionLoad" style="margin-top:10px">Show my 30-day reflection</button><div id="reflectionResult"></div></div><div class="next-card" style="margin-top:10px"><h3>Workflow marketplace</h3><p>First-party curated skills install into Studio; MCP connections remain available under Plugins.</p><div class="next-list">'+market.map(w=>'<div class="next-item"><div class="next-item-main"><b>'+esc(w.name)+'</b><small>'+esc(w.category)+' · '+esc(w.description)+'</small></div><button class="next-btn" data-workflow="'+w.id+'" data-installed="'+(installs.has(w.id)?'1':'0')+'">'+(installs.has(w.id)?'Remove':'Install')+'</button></div>').join('')+'</div></div><div class="next-card" style="margin-top:10px"><h3>Productivity & access</h3><div class="next-row"><button class="next-btn" id="notifyEnable">Enable notifications</button><button class="next-btn" data-install>Install desktop/mobile app</button><a class="next-btn" href="/cli" target="_blank">Open OSAII Code IDE</a><button class="next-btn" id="shortcuts">Keyboard shortcuts</button></div></div>'}
function projectOptions(selected=''){const projects=typeof studio!=='undefined'?studio.projects||[]:[];return projects.map(p=>'<option value="'+esc(p.id)+'" '+(p.id===selected?'selected':'')+'>'+esc(p.name)+'</option>').join('')}
function activeProject(){return typeof studio!=='undefined'?studio.active:null}
function bindView(){
  pqa('[data-next-tab]').forEach(b=>b.onclick=()=>{pstate.tab=b.dataset.nextTab;renderNext()});
  pqa('[data-quick]').forEach(b=>b.onclick=()=>quickMode(b.dataset.quick));pqa('[data-install]').forEach(b=>b.onclick=installPwa);
  pq('#chatSearchGo')?.addEventListener('click',searchChats);pq('#showArchived')?.addEventListener('change',searchChats);
  pqa('[data-chat-open]').forEach(b=>b.onclick=()=>openSyncedChat(b.dataset.chatOpen));pqa('[data-chat-pin]').forEach(b=>b.onclick=()=>chatPatch(b.dataset.chatPin,{pinned:b.dataset.value==='1'}));pqa('[data-chat-more]').forEach(b=>b.onclick=()=>chatMenu(b.dataset.chatMore));
  pq('#memorySave')?.addEventListener('click',saveMemory);pq('#memoryExport')?.addEventListener('click',()=>location.href='/studio/api/platform/memory/export');pq('#memoryImport')?.addEventListener('click',()=>pq('#memoryImportFile').click());pq('#memoryImportFile')?.addEventListener('change',importMemory);pqa('[data-memory-delete]').forEach(b=>b.onclick=()=>deleteMemory(b.dataset.memoryDelete));pqa('[data-memory-pin]').forEach(b=>b.onclick=()=>toggleMemory(b.dataset.memoryPin));
  pq('#fileChoose')?.addEventListener('click',()=>pq('#fileInput').click());pq('#fileInput')?.addEventListener('change',e=>uploadFiles([...e.target.files],pq('#fileProject').value));pqa('[data-file-delete]').forEach(b=>b.onclick=()=>deleteAttachment(b.dataset.fileDelete));
  pq('#researchRun')?.addEventListener('click',runResearch);pq('#researchExport')?.addEventListener('click',()=>downloadText((pstate.research?.report||''),'research-report.md','text/markdown'));
  pq('#canvasContent')?.addEventListener('input',previewCanvas);pq('#canvasKind')?.addEventListener('change',previewCanvas);pq('#canvasSave')?.addEventListener('click',saveCanvas);pq('#canvasShare')?.addEventListener('click',shareCanvas);pq('#canvasExport')?.addEventListener('change',e=>{if(e.target.value)exportDeliverable(e.target.value)});setTimeout(previewCanvas,0);
  pq('#dataOpen')?.addEventListener('click',()=>pq('#dataInput').click());pq('#dataInput')?.addEventListener('change',openData);pq('#dataChart')?.addEventListener('click',drawChart);pq('#dataExport')?.addEventListener('click',()=>exportDeliverable('xlsx'));
  pq('#assistantSave')?.addEventListener('click',saveAssistant);pqa('[data-assistant-use]').forEach(b=>b.onclick=()=>useAssistant(b.dataset.assistantUse));pqa('[data-assistant-remix]').forEach(b=>b.onclick=()=>remixAssistant(b.dataset.assistantRemix));
  pq('#taskCreate')?.addEventListener('click',createTask);pqa('[data-task-run]').forEach(b=>b.onclick=()=>runTaskNow(b.dataset.taskRun));pq('#sessionCreate')?.addEventListener('click',createSession);
  pq('#browserRun')?.addEventListener('click',runBrowser);pq('#profileSave')?.addEventListener('click',saveProfile);pq('#reflectionLoad')?.addEventListener('click',loadReflection);pqa('[data-workflow]').forEach(b=>b.onclick=()=>toggleWorkflow(b));pq('#notifyEnable')?.addEventListener('click',enableNotifications);pq('#shortcuts')?.addEventListener('click',()=>alert('Ctrl/⌘ K: search chats\\nCtrl/⌘ Shift R: research\\nCtrl/⌘ Shift M: memory\\nEscape: close workspace\\nEnter: send, Shift+Enter: newline'));
}
async function loadPlatform(){try{pstate.data=await papi('/bootstrap');mergeSyncedChats();showNotifications();renderNext()}catch{pstate.data=null;renderNext()}}
function mergeSyncedChats(){if(!pstate.data?.chats||typeof loadChats!=='function')return;const local=loadChats(),map=new Map(local.map(c=>[c.id,c]));for(const remote of pstate.data.chats){const existing=map.get(remote.id);if(!existing||new Date(remote.updated_at).getTime()>(existing.updatedAt||0))map.set(remote.id,{id:remote.id,title:remote.title,mode:remote.mode,tier:remote.model==='auto'?'auto':remote.model.includes('laguna-s')?'smart':remote.model.includes('laguna-xs')?'fast':'advanced',advanced:remote.model,reasoning:'low',permission:'low',messages:remote.messages,updatedAt:new Date(remote.updated_at).getTime()})}saveChats([...map.values()].sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0)).slice(0,250));renderHistory()}
async function searchChats(){const q=encodeURIComponent(pq('#chatSearch').value),arch=pq('#showArchived').checked?'1':'0';const d=await papi('/chats?q='+q+'&archived='+arch);pq('#chatResults').innerHTML=chatItems(d.chats);bindView()}
function openSyncedChat(id){const c=pstate.data.chats.find(x=>x.id===id);if(!c)return;const chats=loadChats().filter(x=>x.id!==id);chats.unshift({id:c.id,title:c.title,mode:c.mode,tier:c.model==='auto'?'auto':'fast',advanced:c.model,reasoning:'low',permission:'low',messages:c.messages,updatedAt:Date.now()});saveChats(chats);openChat(id);closeNext()}
async function chatPatch(id,body){await papi('/chats/'+id,{method:'PATCH',body:JSON.stringify(body)});await loadPlatform()}
async function chatMenu(id){const action=prompt('Chat action: rename, archive, branch, share, export, or delete','rename');if(!action)return;if(action==='rename'){const title=prompt('New title');if(title)await chatPatch(id,{title})}else if(action==='archive')await chatPatch(id,{archived:true});else if(action==='branch'){const d=await papi('/chats/'+id+'/branch',{method:'POST',body:'{}'});toast('Branch created');await loadPlatform();openSyncedChat(d.id)}else if(action==='share'){const d=await papi('/chats/'+id+'/share',{method:'POST',body:'{}'});await navigator.clipboard.writeText(location.origin+d.url);toast('Share link copied')}else if(action==='export'){const c=pstate.data.chats.find(x=>x.id===id);downloadText(JSON.stringify(c,null,2),(c?.title||'chat')+'.json','application/json')}else if(action==='delete'&&confirm('Delete this synced chat?')){await papi('/chats/'+id,{method:'DELETE'});await loadPlatform()}}
async function saveMemory(){const content=pq('#memoryText').value.trim();if(!content)return;await papi('/memory',{method:'POST',body:JSON.stringify({content,project_id:pq('#memoryProject').value||null})});toast('Memory saved');await loadPlatform()}
async function deleteMemory(id){if(!confirm('Delete this memory?'))return;await papi('/memory/'+id,{method:'DELETE'});await loadPlatform()}
async function toggleMemory(id){const item=pstate.data.memories.find(x=>x.id===id);await papi('/memory/'+id,{method:'PATCH',body:JSON.stringify({pinned:!Number(item.pinned)})});await loadPlatform()}
async function importMemory(e){const file=e.target.files[0];if(!file)return;await papi('/memory/import',{method:'POST',body:await file.text()});toast('Memory imported');await loadPlatform()}
async function extractFile(file){const name=file.name.toLowerCase(),buffer=await file.arrayBuffer();if(file.type.startsWith('text/')||/\\.(csv|tsv|md|json|txt)$/.test(name))return new TextDecoder().decode(buffer).slice(0,250000);if(/\\.pdf$/.test(name)){const pdf=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs');pdf.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';const doc=await pdf.getDocument({data:buffer}).promise,out=[];for(let i=1;i<=Math.min(doc.numPages,250);i++){const page=await doc.getPage(i),text=await page.getTextContent();out.push(text.items.map(x=>x.str||'').join(' '))}return out.join('\\n').slice(0,250000)}if(/\\.docx?$/.test(name)){await loadScript('https://unpkg.com/mammoth@1.10.0/mammoth.browser.min.js');return (await mammoth.extractRawText({arrayBuffer:buffer})).value.slice(0,250000)}if(/\\.(xlsx?|xls)$/.test(name)){await loadXlsx();const wb=XLSX.read(buffer),parts=[];for(const sheet of wb.SheetNames)parts.push('# '+sheet+'\\n'+XLSX.utils.sheet_to_csv(wb.Sheets[sheet]));return parts.join('\\n').slice(0,250000)}if(/\\.pptx$/.test(name)){await loadZip();const zip=await JSZip.loadAsync(buffer),parts=[];for(const key of Object.keys(zip.files).filter(x=>/^ppt\\/slides\\/slide\\d+\\.xml$/.test(x)).sort()){const xml=await zip.file(key).async('text');parts.push(xml.replace(/<a:br\\s*\\/>/g,'\\n').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&'))}return parts.join('\\n').slice(0,250000)}return ''}
async function uploadFiles(files,projectId=''){if(!files.length)return;const status=pq('#fileStatus');for(const file of files){try{if(status)status.textContent='Reading '+file.name+'…';const extracted=await extractFile(file);if(!state.chatId)state.chatId=crypto.randomUUID();const meta=await papi('/attachments',{method:'POST',body:JSON.stringify({name:file.name,content_type:file.type||'application/octet-stream',size:file.size,chat_id:state.chatId,project_id:projectId||activeProject()?.id||null,extracted_text:extracted})});const response=await fetch(meta.upload_url,{method:'PUT',credentials:'same-origin',headers:{'content-type':file.type||'application/octet-stream','content-length':String(file.size)},body:file});if(!response.ok)throw new Error('Upload failed');pstate.pending.push({id:meta.id,name:file.name,type:file.type,text:extracted,file});if(status)status.textContent='Ready: '+file.name;renderAttachmentPills()}catch(error){if(status)status.textContent=file.name+': '+error.message}}await loadPlatform()}
function renderAttachmentPills(){let host=pq('#nextAttachments');if(!host){host=document.createElement('div');host.id='nextAttachments';host.className='next-attachments';pq('.box')?.prepend(host)}host.innerHTML=pstate.pending.map((x,i)=>'<span class="next-attachment">📎 '+esc(x.name)+' <button data-pending-remove="'+i+'" aria-label="Remove">×</button></span>').join('');pqa('[data-pending-remove]').forEach(b=>b.onclick=()=>{pstate.pending.splice(Number(b.dataset.pendingRemove),1);renderAttachmentPills()})}
async function deleteAttachment(id){if(!confirm('Delete this uploaded file?'))return;await papi('/attachments/'+id,{method:'DELETE'});await loadPlatform()}
async function runResearch(){const button=pq('#researchRun'),status=pq('#researchStatus');button.disabled=true;status.textContent='Planning and browsing multiple sources…';pstate.research={question:pq('#researchQuestion').value,plan:pq('#researchPlan').value,status:'Researching…'};try{const d=await papi('/research',{method:'POST',body:JSON.stringify({question:pstate.research.question,plan:pstate.research.plan,domains:pq('#researchDomains').value.split(',').map(x=>x.trim()).filter(Boolean),project_id:activeProject()?.id})});pstate.research={...pstate.research,report:d.report,status:'Complete · cited report ready'};renderNext();toast('Research complete')}catch(e){status.textContent=e.message;button.disabled=false}}
function previewCanvas(){const content=pq('#canvasContent')?.value||'',kind=pq('#canvasKind')?.value||'document',frame=pq('#canvasPreview');if(!frame)return;frame.srcdoc=kind==='app'||kind==='code'?content:'<!doctype html><style>body{font:16px/1.7 system-ui;padding:28px;white-space:pre-wrap;color:#171717}</style>'+esc(content)}
async function saveCanvas(){const body={id:pstate.document?.id,title:pq('#canvasTitle').value,kind:pq('#canvasKind').value,content:pq('#canvasContent').value,project_id:activeProject()?.id};const d=await papi('/documents',{method:'POST',body:JSON.stringify(body)});pstate.document={...body,id:d.id};toast('Canvas saved');await loadPlatform()}
async function shareCanvas(){if(!pstate.document?.id)await saveCanvas();const d=await papi('/documents/'+pstate.document.id+'/share',{method:'POST',body:'{}'});await navigator.clipboard.writeText(location.origin+d.url);toast('Share link copied')}
async function loadScript(src){if(document.querySelector('script[data-src="'+src+'"]'))return new Promise(resolve=>{const ready=()=>window.JSZip||window.XLSX||window.jspdf||window.mammoth?resolve():setTimeout(ready,50);ready()});return new Promise((resolve,reject)=>{const s=document.createElement('script');s.dataset.src=src;s.src=src;s.onload=resolve;s.onerror=reject;document.head.append(s)})}
const loadZip=()=>loadScript('https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js'),loadXlsx=()=>loadScript('https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js');
async function exportDeliverable(kind){const title=(pq('#canvasTitle')?.value||'OSS Studio deliverable').replace(/[^a-z0-9_-]+/gi,'-'),content=pq('#canvasContent')?.value||tableCsv();if(kind==='txt'||kind==='html'){downloadText(content,title+'.'+kind,kind==='html'?'text/html':'text/plain');return}if(kind==='pdf'){await loadScript('https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.2/jspdf.umd.min.js');const doc=new jspdf.jsPDF(),lines=doc.splitTextToSize(content,180);let y=16;for(const line of lines){if(y>280){doc.addPage();y=16}doc.text(line,15,y);y+=6}doc.save(title+'.pdf');return}if(kind==='xlsx'){await loadXlsx();const wb=XLSX.utils.book_new(),rows=pstate.dataRows.length?pstate.dataRows:content.split('\\n').map(x=>[x]);XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(rows),'Studio');XLSX.writeFile(wb,title+'.xlsx');return}await loadZip();const zip=new JSZip();if(kind==='docx')buildDocx(zip,title,content);else buildPptx(zip,title,content);const blob=await zip.generateAsync({type:'blob',mimeType:kind==='docx'?'application/vnd.openxmlformats-officedocument.wordprocessingml.document':'application/vnd.openxmlformats-officedocument.presentationml.presentation'});downloadBlob(blob,title+'.'+kind)}
function buildDocx(zip,title,content){zip.file('[Content_Types].xml','<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>');zip.folder('_rels').file('.rels','<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>');const paras=(title+'\\n'+content).split('\\n').map(x=>'<w:p><w:r><w:t xml:space="preserve">'+xml(x)+'</w:t></w:r></w:p>').join('');zip.folder('word').file('document.xml','<?xml version="1.0"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>'+paras+'<w:sectPr/></w:body></w:document>')}
function buildPptx(zip,title,content){zip.file('[Content_Types].xml','<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/><Override PartName="/ppt/slides/slide1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/></Types>');zip.folder('_rels').file('.rels','<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="ppt/presentation.xml"/></Relationships>');zip.folder('ppt').file('presentation.xml','<?xml version="1.0"?><p:presentation xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:sldIdLst><p:sldId id="256" r:id="rId1"/></p:sldIdLst><p:sldSz cx="9144000" cy="5143500"/></p:presentation>');zip.folder('ppt').folder('_rels').file('presentation.xml.rels','<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide1.xml"/></Relationships>');const text=xml(title+'\\n'+content.slice(0,4500));zip.folder('ppt').folder('slides').file('slide1.xml','<?xml version="1.0"?><p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:cSld><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr/><p:sp><p:nvSpPr><p:cNvPr id="2" name="Text"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr><p:spPr><a:xfrm><a:off x="457200" y="457200"/><a:ext cx="8229600" cy="4114800"/></a:xfrm></p:spPr><p:txBody><a:bodyPr/><a:lstStyle/><a:p><a:r><a:rPr lang="en-US" sz="2400"/><a:t>'+text+'</a:t></a:r></a:p></p:txBody></p:sp></p:spTree></p:cSld></p:sld>')}
function xml(s){return esc(s)}
async function openData(e){const file=e.target.files[0];if(!file)return;await loadXlsx();const wb=XLSX.read(await file.arrayBuffer()),sheet=wb.Sheets[wb.SheetNames[0]];pstate.dataRows=XLSX.utils.sheet_to_json(sheet,{header:1,raw:false}).slice(0,10000);renderDataTable();toast('Loaded '+pstate.dataRows.length+' rows')}
function renderDataTable(){const rows=pstate.dataRows,host=pq('#dataTable'),select=pq('#chartColumn');if(!rows.length)return;select.innerHTML=(rows[0]||[]).map((x,i)=>'<option value="'+i+'">'+esc(x||'Column '+(i+1))+'</option>').join('');host.innerHTML='<table class="next-table">'+rows.slice(0,100).map((r,i)=>'<tr>'+r.map(x=>(i?'<td>':'<th>')+esc(x)+(i?'</td>':'</th>')).join('')+'</tr>').join('')+'</table><small>Showing first 100 of '+rows.length+' rows.</small>'}
function drawChart(){const canvas=pq('#dataCanvas'),ctx=canvas.getContext('2d'),column=Number(pq('#chartColumn').value),values=pstate.dataRows.slice(1,31).map(r=>Number(String(r[column]||'').replace(/[^0-9.-]/g,''))).filter(Number.isFinite),max=Math.max(...values,1);ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#34d17e';values.forEach((v,i)=>{const h=(v/max)*(canvas.height-40),w=Math.max(4,(canvas.width-40)/values.length-4);ctx.fillRect(20+i*((canvas.width-40)/values.length),canvas.height-20-h,w,h)});ctx.fillStyle='#a7a7a0';ctx.font='14px system-ui';ctx.fillText((pstate.dataRows[0]||[])[column]||'Values',18,18)}
function tableCsv(){return pstate.dataRows.map(r=>r.map(x=>'"'+String(x||'').replace(/"/g,'""')+'"').join(',')).join('\\n')}
async function saveAssistant(){const body={name:pq('#assistantName').value,description:pq('#assistantDescription').value,instructions:pq('#assistantInstructions').value,visibility:pq('#assistantVisibility').value,knowledge_ids:(pstate.data.attachments||[]).filter(x=>x.project_id===activeProject()?.id).map(x=>x.id)};await papi('/assistants',{method:'POST',body:JSON.stringify(body)});toast('Assistant created');await loadPlatform()}
function useAssistant(id){pstate.assistant=pstate.data.assistants.find(x=>x.id===id);toast('Using '+pstate.assistant.name+' in chat');closeNext();pq('#prompt').focus()}
async function remixAssistant(id){await papi('/assistants/'+id,{method:'POST',body:'{}'});toast('Assistant remixed');await loadPlatform()}
async function createTask(){const d=await papi('/tasks',{method:'POST',body:JSON.stringify({title:pq('#taskTitle').value,prompt:pq('#taskPrompt').value,kind:pq('#taskKind').value,schedule:pq('#taskSchedule').value,project_id:activeProject()?.id,next_run:new Date(Date.now()+60000).toISOString()})});toast('Task scheduled');await papi('/tasks/'+d.id+'/run',{method:'POST',body:'{}'});await loadPlatform()}
async function runTaskNow(id){await papi('/tasks/'+id+'/run',{method:'POST',body:'{}'});toast('Task running in the cloud');await loadPlatform()}
async function createSession(){const promptText=prompt('What should the managed coding team work on?','Review this project and produce an implementation plan with tests.');if(!promptText)return;const d=await papi('/sessions',{method:'POST',body:JSON.stringify({kind:'multi-agent',title:promptText.slice(0,100),project_id:activeProject()?.id,state:{agents:[],workspace:'isolated'}})});await papi('/sessions/'+d.id+'/run',{method:'POST',body:JSON.stringify({prompt:promptText})});await navigator.clipboard.writeText(location.origin+d.control_url);toast('Four managed coding roles launched; control link copied');await loadPlatform()}
async function runBrowser(){const action=pq('#browserAction').value,needs=action!=='navigate',confirmed=!needs||confirm('Allow cloud browser to '+action+' on this page?');if(!confirmed)return;const status=pq('#browserStatus');status.textContent='Cloud browser is working…';try{const d=await papi('/browser/action',{method:'POST',body:JSON.stringify({session_id:pstate.browserSession,url:pq('#browserUrl').value,action,selector:pq('#browserSelector').value,value:pq('#browserValue').value,confirmed})});pstate.browserSession=d.session_id;status.textContent=d.title+' · '+d.url;const img=pq('#browserShot');img.src=d.screenshot+'?t='+Date.now();img.style.display='block'}catch(e){status.textContent=e.message}}
async function saveProfile(){await papi('/profile',{method:'PATCH',body:JSON.stringify({custom_instructions:pq('#customInstructions').value,memory_enabled:pq('#memoryEnabled').checked,preferences:{theme:document.body.classList.contains('light')?'light':'dark'}})});toast('Preferences saved');await loadPlatform()}
async function loadReflection(){const d=await papi('/reflection'),host=pq('#reflectionResult');host.innerHTML='<div class="next-status">'+d.chats+' chats in 30 days · frequent topics: '+d.topics.map(x=>esc(x.topic)+' ('+x.count+')').join(', ')+'</div>'}
async function toggleWorkflow(button){await papi('/marketplace/install',{method:'POST',body:JSON.stringify({workflow_id:button.dataset.workflow,installed:button.dataset.installed!=='1'})});toast(button.dataset.installed==='1'?'Workflow removed':'Workflow installed');await loadPlatform()}
function quickMode(kind){if(kind==='study'){pstate.assistant={name:'Study mode',instructions:'Teach adaptively with Socratic questions. Ask one diagnostic question at a time, adjust difficulty, do not reveal the answer before the learner attempts it, then explain clearly.'};state.mode='chat';closeNext();pq('#prompt').placeholder='What would you like to learn?';pq('#prompt').focus()}else if(kind==='meeting'){closeNext();startMicrophone(true)}else location.href='/cli'}
let deferredInstall;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e});async function installPwa(){if(deferredInstall){await deferredInstall.prompt();deferredInstall=null}else toast('Use your browser menu → Install OSS Studio / Add to Home Screen')}
async function enableNotifications(){if(!('Notification'in window)){toast('Notifications are not supported here');return}const permission=await Notification.requestPermission();toast(permission==='granted'?'Notifications enabled':'Notifications were not enabled')}
function showNotifications(){for(const n of pstate.data?.notifications||[]){if(Number(n.read)||pstate.notified.has(n.id))continue;pstate.notified.add(n.id);toast(n.title+': '+n.body);if(Notification.permission==='granted')new Notification(n.title,{body:n.body,icon:'/osaii.png'})}}
async function grounding(){if(!pstate.data)return '';const project=activeProject()?.id,profile=pstate.data.profile||{},mem=(pstate.data.memories||[]).filter(x=>!x.project_id||x.project_id===project).slice(0,40).map(x=>'- '+x.content).join('\\n'),files=(pstate.data.attachments||[]).filter(x=>x.extracted_text&&(!x.project_id||x.project_id===project)).slice(0,15).map(x=>'FILE '+x.name+':\\n'+x.extracted_text).join('\\n\\n');return ['User custom instructions:',profile.custom_instructions||'(none)','Relevant personal and project memory:',mem||'(none)','Project knowledge and attachments:',files||'(none)',pstate.assistant?'Active custom assistant '+pstate.assistant.name+':\\n'+pstate.assistant.instructions:''].join('\\n\\n').slice(0,110000)}
function autoRoute(messages){const text=messages.map(x=>ptext(x.content)).join(' ').toLowerCase(),hard=/\\b(analy[sz]e|prove|research|architecture|debug|strategy|compare|complex|codebase|reason)\\b/.test(text)||text.length>1800;return hard?'poolside/laguna-s-2.1':'poolside/laguna-xs-2.1'}
async function augment(messages,model){const context=await grounding(),next=[...messages];if(context)next.unshift({role:'system',content:'OSS Studio context. Use it when relevant; do not mention hidden context unless asked.\\n\\n'+context});if(pstate.pending.length){const last=[...next].reverse().find(x=>x.role==='user');if(last){const pieces=[{type:'text',text:ptext(last.content)}];for(const a of pstate.pending){if(a.type.startsWith('image/'))pieces.push({type:'image_url',image_url:{url:await fileDataUrl(a.file)}});else if(a.text)pieces.push({type:'text',text:'Attachment '+a.name+':\\n'+a.text})}last.content=pieces}}return{messages:next,model:state.tier==='auto'?autoRoute(next):model}}
function fileDataUrl(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)})}
function syncChat(){if(!pstate.data||!state.chatId||!state.messages.some(x=>x.role==='user'))return;const local=loadChats().find(x=>x.id===state.chatId);papi('/chats',{method:'POST',body:JSON.stringify({id:state.chatId,project_id:activeProject()?.id,assistant_id:pstate.assistant?.id,title:local?.title||'New conversation',mode:state.mode,model:state.tier==='auto'?'auto':selectedModel(),messages:state.messages})}).catch(()=>{});autoRemember();if(pstate.voiceReplies)setTimeout(speakLatest,120)}
function autoRemember(){if(Number(pstate.data?.profile?.memory_enabled)===0)return;const last=[...state.messages].reverse().find(x=>x.role==='user'),text=ptext(last?.content).trim();if(!text||!/\\b(remember that|please remember|i prefer|my name is|always use|never use)\\b/i.test(text)||pstate.autoRemembered===text)return;pstate.autoRemembered=text;papi('/memory',{method:'POST',body:JSON.stringify({content:text,project_id:activeProject()?.id||null,source:'chat'})}).then(loadPlatform).catch(()=>{})}
function addComposerControls(){const tools=pq('.tools');if(!tools||pq('#nextAttach'))return;const attach=document.createElement('button');attach.id='nextAttach';attach.type='button';attach.className='next-composer-btn';attach.textContent='＋ File';attach.onclick=()=>{if(!pstate.data){openNext('home');return}const input=document.createElement('input');input.type='file';input.multiple=true;input.accept='.pdf,.doc,.docx,.pptx,.xls,.xlsx,.csv,.tsv,.txt,.md,.json,image/*';input.onchange=()=>uploadFiles([...input.files],activeProject()?.id||'');input.click()};const mic=document.createElement('button');mic.type='button';mic.className='next-composer-btn';mic.textContent='◉ Voice';mic.onclick=()=>startMicrophone(false);const video=document.createElement('button');video.type='button';video.className='next-composer-btn';video.textContent='▣ Live';video.onclick=mediaMenu;tools.insertBefore(attach,tools.querySelector('.right'));tools.insertBefore(mic,tools.querySelector('.right'));tools.insertBefore(video,tools.querySelector('.right'))}
let recognition,meetingParts=[];function startMicrophone(meeting){const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SpeechRecognition){toast('Speech recognition is unavailable in this browser');return}pstate.voiceReplies=true;recognition=new SpeechRecognition();recognition.continuous=meeting;recognition.interimResults=true;recognition.onresult=e=>{let final='';for(let i=e.resultIndex;i<e.results.length;i++)if(e.results[i].isFinal)final+=e.results[i][0].transcript;if(final){if(meeting)meetingParts.push(final);pq('#prompt').value=(pq('#prompt').value+' '+final).trim()}};recognition.onend=()=>{if(meeting&&meetingParts.length){pq('#prompt').value='Create meeting notes with summary, decisions, action items, owners, and open questions from this transcript:\\n\\n'+meetingParts.join(' ');toast('Meeting transcript ready to send')}};recognition.start();toast(meeting?'Meeting recording started':'Voice conversation started · responses will be spoken')}
async function mediaMenu(){const choice=prompt('Live mode: camera or screen','screen');if(!choice)return;try{const stream=choice==='camera'?await navigator.mediaDevices.getUserMedia({video:true,audio:true}):await navigator.mediaDevices.getDisplayMedia({video:true,audio:true});const box=pq('#nextMedia'),video=box.querySelector('video');video.srcObject=stream;box.hidden=false;pq('#mediaStop').onclick=()=>{stream.getTracks().forEach(x=>x.stop());box.hidden=true};pq('#mediaAttach').onclick=async()=>{const canvas=document.createElement('canvas');canvas.width=video.videoWidth||1280;canvas.height=video.videoHeight||720;canvas.getContext('2d').drawImage(video,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.86)),file=new File([blob],'live-frame.jpg',{type:'image/jpeg'});await uploadFiles([file],activeProject()?.id||'');toast('Live frame attached to chat')}}catch(e){toast(e.message)}}
function speakLatest(){if(!('speechSynthesis'in window))return;const messages=pqa('.message.assistant'),last=messages[messages.length-1],text=last?.textContent.trim();if(!text||pstate.lastSpoken===text)return;pstate.lastSpoken=text;const utterance=new SpeechSynthesisUtterance(text.slice(0,12000));speechSynthesis.cancel();speechSynthesis.speak(utterance)}
function downloadText(text,name,type){downloadBlob(new Blob([text],{type}),name)}function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}function formatBytes(n){return n>1048576?(n/1048576).toFixed(1)+' MB':n>1024?(n/1024).toFixed(1)+' KB':n+' B'}
function setup(){const side=pq('.side'),history=pq('.history');if(side&&history&&!pq('#nextOpen')){const search=document.createElement('input');search.id='nextQuickSearch';search.className='next-search';search.placeholder='Search chats  ⌘K';search.onclick=()=>openNext('chats');history.before(search);const launch=document.createElement('button');launch.id='nextOpen';launch.className='next-launch';launch.innerHTML='<b>✦</b> Workspaces & tools';launch.onclick=()=>openNext('home');search.after(launch)}addComposerControls();const speed=pq('#speed');if(speed&&!speed.querySelector('option[value="auto"]')){const option=document.createElement('option');option.value='auto';option.textContent='Auto';speed.prepend(option);const previous=speed.onchange;speed.onchange=e=>{if(e.target.value==='auto'){state.tier='auto';state.chatgptMode=false;renderModelControls();e.target.value='auto';pq('#modelLabel').textContent='AUTO · task routing'}else previous?.call(speed,e)}}const oldRender=renderModelControls;renderModelControls=()=>{oldRender();if(state.tier==='auto'){speed.value='auto';pq('#modelLabel').textContent='AUTO · task routing'}};const oldAskStream=askStream;askStream=async(messages,model,onDelta,onReasoning)=>{const next=await augment(messages,model);return oldAskStream(next.messages,next.model,onDelta,onReasoning)};const oldAsk=ask;ask=async(messages,model)=>{const next=await augment(messages,model);return oldAsk(next.messages,next.model)};const oldSave=saveCurrentChat;saveCurrentChat=()=>{oldSave();syncChat()};const oldNew=newChat;newChat=()=>{pstate.pending=[];pstate.assistant=null;renderAttachmentPills();oldNew()};window.__ossStudioPlatform=pstate;window.__ossAutoRoute=autoRoute;renderModelControls();if('serviceWorker'in navigator)navigator.serviceWorker.register('/studio/new/sw.js',{scope:'/studio/new'}).catch(()=>{});loadPlatform();setInterval(loadPlatform,30000)}
document.body.insertAdjacentHTML('beforeend','<div class="next-backdrop" id="nextBackdrop"></div><aside class="next-drawer" id="nextDrawer" aria-hidden="true"><div class="next-head"><div><small>OSS Studio</small><h2>Workspaces</h2></div><span class="next-spacer"></span><button class="next-icon" id="nextClose" aria-label="Close">×</button></div><nav class="next-tabs" id="nextTabs"></nav><div class="next-body" id="nextBody"></div></aside><div class="next-media" id="nextMedia" hidden><video autoplay playsinline></video><div class="next-row" style="margin-top:8px"><button class="next-btn primary" id="mediaAttach">Attach live frame</button><button class="next-btn" id="mediaStop">Stop sharing</button></div></div><div class="next-notify" id="nextNotify"></div>');
pq('#nextClose').onclick=closeNext;pq('#nextBackdrop').onclick=closeNext;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeNext();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openNext('chats')}if((e.ctrlKey||e.metaKey)&&e.shiftKey&&e.key.toLowerCase()==='r'){e.preventDefault();openNext('research')}if((e.ctrlKey||e.metaKey)&&e.shiftKey&&e.key.toLowerCase()==='m'){e.preventDefault();openNext('memory')}});
const messageObserver=new MutationObserver(()=>{pqa('.message.assistant a[href]').forEach(a=>a.classList.add('next-source'))});messageObserver.observe(pq('#feed'),{subtree:true,childList:true});
setup();
})();</script>`;

export function studioNewPage(): string {
  return appPage()
    .replace("<title>OSS Studio</title>", "<title>OSS Studio · Workspaces</title>")
    .replace(
      "Never perform a read solely to verify a successful write.",
      "Never perform a read solely to verify a successful write. When web search is used, cite visible source titles and full URLs in the final answer.",
    )
    .replace(
      "model:agentModel(),surface:'agent'",
      "model:state.tier==='auto'&&window.__ossAutoRoute?window.__ossAutoRoute(messages):agentModel(),surface:'agent'",
    )
    .replace("</head>", '<link rel="manifest" href="/studio/new/manifest.webmanifest">' + STYLE + "</head>")
    .replace("</body></html>", SCRIPT + "</body></html>");
}

export function studioManifest(): string {
  return JSON.stringify({ name: "OSS Studio", short_name: "OSS Studio", description: "Synced AI chat, research, projects, agents, and creative workspaces.", start_url: "/studio/new", scope: "/studio/new", display: "standalone", background_color: "#000000", theme_color: "#000000", icons: [{ src: "/osaii.png", sizes: "512x512", type: "image/png", purpose: "any maskable" }] });
}

export function studioServiceWorker(): string {
  return `const CACHE='oss-studio-shell-v1';self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(['/studio/new','/osaii.png','/studio/new/manifest.webmanifest'])).then(()=>self.skipWaiting())));self.addEventListener('activate',event=>event.waitUntil(self.clients.claim()));self.addEventListener('fetch',event=>{const url=new URL(event.request.url);if(event.request.method!=='GET'||url.pathname.startsWith('/studio/api/'))return;event.respondWith(fetch(event.request).then(response=>{if(response.ok&&url.origin===location.origin)caches.open(CACHE).then(cache=>cache.put(event.request,response.clone()));return response}).catch(()=>caches.match(event.request)))})`;
}
